name: connecty
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter_bloc: ^7.0.0
  test: ^1.15.2
  bloc_test: ^8.0.0
  equatable: ^2.0.0
  curved_navigation_bar: ^0.3.4
  font_awesome_flutter: ^9.0.0
  google_fonts: ^2.0.0
  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4
  cloud_firestore: ^1.0.7
  shared_preferences: ^2.0.5
  pedantic: ^1.9.0
  page_transition: ^2.0.2
  animated_text_kit: ^4.2.1
  beauty_textfield: ^0.0.1
  image_picker: ^0.7.4
  loading_indicator: ^2.0.1
  mockito: ^5.0.8
  material_floating_search_bar: ^0.3.4
  easy_localization: ^3.0.0
  country_icons: ^2.0.2
  shimmer: ^1.1.0
  flutter_slidable: ^0.5.7
  timeago: ^3.1.0
  glassmorphism: ^3.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  fab_circular_menu: ^1.0.2
  alphabet_list_scroll_view: ^2.0.0
  flare_flutter: ^3.0.2
  sleek_circular_slider: ^2.0.1
  flutter_sliding_tutorial: ^1.1.3
  flutter_svg: ^1.0.0

  authentication:
    path: lib/repositories/authentication
  users:
    path: lib/repositories/users
  storage:
    path: lib/repositories/storage
  data:
    path: lib/repositories/data

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/langs/
